trigger:
  - master

pool:
  name: Default

steps:
  - script: echo Hello, it's my Azure Devops App
    displayName: 'Run an echo command'

  - script: mvn clean install
    displayName: 'Build with Maven'

  - script: java -jar target/krish5-0.0.1-SNAPSHOT.jar
    displayName: 'Run the JAR file of my krish5 App'
